[package]
name = "gang-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
bevy_reflect=[]

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
derive_more = "0.99"
